version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./rules.yml:/etc/prometheus/rules.yml"
    networks:
      - opensis_network
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter
    networks:
      - opensis_network
    ports:
      - "9100:9100"

  alert-manager:
    image: quay.io/prometheus/alertmanager
    volumes:
      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - opensis_network
    ports:
      - "9093:9093"

  database:
    image: mariadb:10.5
    container_name: opensis-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_DATABASE: "openSIS"
      MYSQL_USER: "openSIS_rw"
      MYSQL_PASSWORD: "admin101"
    volumes:
      - db_data:/var/lib/mysql
      - ./openSIS-Classic/MYSQL/mysql-init:/docker-entrypoint-initdb.d
      - ./openSIS-Classic/MYSQL/mysql-config/strict_mode.cnf:/etc/mysql/conf.d/strict_mode.cnf
    networks:
      - opensis_network

  opensis-ui:
    image: opensis-ui
    container_name: opensis-ui
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    networks:
      - opensis_network

  grafana_postgres:
    container_name: grafana_postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: grafana_db
      POSTGRES_USER: grafana_usr
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    networks:
      - opensis_network

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: grafana_postgres
      GF_DATABASE_NAME: grafana_db
      GF_DATABASE_USER: grafana_usr
      GF_DATABASE_PASSWORD: admin123
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - opensis_network

volumes:
  db_data:
  grafana-storage: {}
  postgres-storage: {}

networks:
  opensis_network:
    driver: bridge
